In [ ]:
import numpy as np

#2D numpy Array
np.random.seed(5)
val= np.random.randint(10,50, size=(3,5))
# val.mean
print(val)

[[45 24 48 26 19]
 [18 46 49 37 40]
 [26 17 22 25 49]]


In [ ]:
val[2:,:3]

array([[26, 17, 22]])

In [ ]:
#step 1
old_matrix=np.random.randint(0,100, size=(9,9))
print(old_matrix)



[[37 12 72  9 75  5 79 64 16]
 [ 1 76 71  6 25 50 20 18 84]
 [11 28 29 14 50 68 87 87 94]
 [96 86 13  9  7 63 61 22 57]
 [ 1  0 60 81  8 88 13 47 72]
 [30 71  3 70 21 49 57  3 68]
 [24 43 76 26 52 80 41 82 15]
 [64 68 25 98 87  7 26 25 22]
 [ 9 67 23 27 37 57 83 38  8]]


In [ ]:
new_matrix=np.zeros((old_matrix.shape[0],old_matrix.shape[1]))
mean_matrix=[]

zeros=0
non_zeros=0
print("Old Matrix\n",old_matrix)
for i in range(old_matrix.shape[0]):
 #step 2
  mean=old_matrix[i,:].mean()
  mean_matrix.append(mean)
#step 3
  for j in range (old_matrix.shape[1]):
    if old_matrix[i,j] < mean_matrix[i]:
      new_matrix[i,j]=old_matrix[i,j]
      zeros+=1
    else:
      new_matrix[i,j]=0;
      non_zeros+=1

print("\n", mean_matrix, "\n")
print("\nUpdated Matrix\n",new_matrix)

#step4
if (zeros+non_zeros==old_matrix.size):
  print("Updated matrix verified")


Old Matrix
 [[37 12 72  9 75  5 79 64 16]
 [ 1 76 71  6 25 50 20 18 84]
 [11 28 29 14 50 68 87 87 94]
 [96 86 13  9  7 63 61 22 57]
 [ 1  0 60 81  8 88 13 47 72]
 [30 71  3 70 21 49 57  3 68]
 [24 43 76 26 52 80 41 82 15]
 [64 68 25 98 87  7 26 25 22]
 [ 9 67 23 27 37 57 83 38  8]]

 [41.0, 39.0, 52.0, 46.0, 41.111111111111114, 41.333333333333336, 48.77777777777778, 46.888888888888886, 38.77777777777778] 


Updated Matrix
 [[37. 12.  0.  9.  0.  5.  0.  0. 16.]
 [ 1.  0.  0.  6. 25.  0. 20. 18.  0.]
 [11. 28. 29. 14. 50.  0.  0.  0.  0.]
 [ 0.  0. 13.  9.  7.  0.  0. 22.  0.]
 [ 1.  0.  0.  0.  8.  0. 13.  0.  0.]
 [30.  0.  3.  0. 21.  0.  0.  3.  0.]
 [24. 43.  0. 26.  0.  0. 41.  0. 15.]
 [ 0.  0. 25.  0.  0.  7. 26. 25. 22.]
 [ 9.  0. 23. 27. 37.  0.  0. 38.  8.]]
Updated matrix verified


In [101]:
siz=4
np.random.seed(5)
algo=np.random.randint(1,99,size=(siz,siz))
print("Input Matrix\n",algo)
result=np.zeros((int(algo.shape[0]/2),int(algo.shape[0]/2)))
indi=-1
indj=-1
for i in range(0,algo.shape[0],2):
  indi+=1
  indj-=1
  for j in range(0,algo.shape[1],2):
    indj+=1
    # indi-=1
    temp= algo[i:i+2,j:j+2]
    v=temp.max()
    result[indi,indj]=v
    print()
    # print(temp)
print("final Result")
print(result)

Input Matrix
 [[79 62 17 74]
 [ 9 63 28 31]
 [81  8 77 16]
 [54 81 28 45]]




final Result
[[74. 79.]
 [81. 77.]]


In [108]:
import pandas as pd

data =pd.read_csv('./ign.csv')
print(type(data))
print(data.shape)

data.head()

<class 'pandas.core.frame.DataFrame'>
(18625, 10)


score_phrase                                              title  \
0      Amazing                            LittleBigPlanet PS Vita   
1      Amazing  LittleBigPlanet PS Vita -- Marvel Super Hero E...   
2        Great                               Splice: Tree of Life   
3        Great                                             NHL 13   
4        Great                                             NHL 13   

                                                 url          platform  score  \
0             /games/littlebigplanet-vita/vita-98907  PlayStation Vita    9.0   
1  /games/littlebigplanet-ps-vita-marvel-super-he...  PlayStation Vita    9.0   
2                          /games/splice/ipad-141070              iPad    8.5   
3                      /games/nhl-13/xbox-360-128182          Xbox 360    8.5   
4                           /games/nhl-13/ps3-128181     PlayStation 3    8.5   

        genre editors_choice  release_year  release_month  release_day  
0  Platformer              Y          2012              9           12  
1  Platformer              Y          2012              9           12  
2      Puzzle              N          2012              9           12  
3      Sports              N          2012              9           11  
4      Sports              N          2012              9           11

from matplotlib import pyplot as plt
_df_0['score'].plot(kind='hist', bins=20, title='score')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['release_day'].plot(kind='hist', bins=20, title='release_day')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_2.groupby('score_phrase').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_3.groupby('title').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_4.groupby('url').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_5.groupby('platform').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_6.plot(kind='scatter', x='score', y='release_day', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['release_year']
  ys = series['score']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_7.sort_values('release_year', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('score_phrase')):
  _plot_series(series, series_name, i)
  fig.legend(title='score_phrase', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('release_year')
_ = plt.ylabel('score')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['release_year']
  ys = series['score']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_8.sort_values('release_year', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('title')):
  _plot_series(series, series_name, i)
  fig.legend(title='title', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('release_year')
_ = plt.ylabel('score')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['release_year']
  ys = series['score']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_9.sort_values('release_year', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('url')):
  _plot_series(series, series_name, i)
  fig.legend(title='url', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('release_year')
_ = plt.ylabel('score')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['release_year']
  ys = series['score']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_10.sort_values('release_year', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('platform')):
  _plot_series(series, series_name, i)
  fig.legend(title='platform', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('release_year')
_ = plt.ylabel('score')

from matplotlib import pyplot as plt
_df_11['score'].plot(kind='line', figsize=(8, 4), title='score')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_12['release_day'].plot(kind='line', figsize=(8, 4), title='release_day')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['title'].value_counts()
    for x_label, grp in _df_13.groupby('score_phrase')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('score_phrase')
_ = plt.ylabel('title')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['url'].value_counts()
    for x_label, grp in _df_14.groupby('title')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('title')
_ = plt.ylabel('url')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['platform'].value_counts()
    for x_label, grp in _df_15.groupby('url')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('url')
_ = plt.ylabel('platform')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['genre'].value_counts()
    for x_label, grp in _df_16.groupby('platform')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('platform')
_ = plt.ylabel('genre')

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_17['score_phrase'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_17, x='score', y='score_phrase', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_18['title'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_18, x='score', y='title', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_19['url'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_19, x='score', y='url', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_20['platform'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_20, x='score', y='platform', inner='stick', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

In [110]:
data.iloc[2:5,[0,2,4]]

score_phrase                            url  score
2        Great      /games/splice/ipad-141070    8.5
3        Great  /games/nhl-13/xbox-360-128182    8.5
4        Great       /games/nhl-13/ps3-128181    8.5

In [111]:
data.loc[2:5,["score_phrase","score"]]

score_phrase  score
2        Great    8.5
3        Great    8.5
4        Great    8.5
5         Good    7.0

In [113]:
data['score']

0         9.0
1         9.0
2         8.5
3         8.5
4         8.5
         ... 
18620     7.6
18621     9.0
18622     5.8
18623    10.0
18624    10.0
Name: score, Length: 18625, dtype: float64

In [114]:
data[['title','score']]

title  score
0                                LittleBigPlanet PS Vita    9.0
1      LittleBigPlanet PS Vita -- Marvel Super Hero E...    9.0
2                                   Splice: Tree of Life    8.5
3                                                 NHL 13    8.5
4                                                 NHL 13    8.5
...                                                  ...    ...
18620                          Tokyo Mirage Sessions #FE    7.6
18621                  LEGO Star Wars: The Force Awakens    9.0
18622            Star Ocean: Integrity and Faithlessness    5.8
18623                                             Inside   10.0
18624                                             Inside   10.0

[18625 rows x 2 columns]

In [116]:
data.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18625 entries, 0 to 18624
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   score_phrase    18625 non-null  object 
 1   title           18625 non-null  object 
 2   url             18625 non-null  object 
 3   platform        18625 non-null  object 
 4   score           18625 non-null  float64
 5   genre           18589 non-null  object 
 6   editors_choice  18625 non-null  object 
 7   release_year    18625 non-null  int64  
 8   release_month   18625 non-null  int64  
 9   release_day     18625 non-null  int64  
dtypes: float64(1), int64(3), object(6)
memory usage: 1.4+ MB


In [117]:
score = data['score']
avg=score.mean()
min=score.min()
max=score.max()
var=score.var()
std=score.std()

print("Varinece: ",var)
print("Average: ",avg)
print("Maximum: ",max)
print("Minimum: ",min)
print("Standard Deviation: ",std)

Varinece:  2.9300396571646026
Average:  6.950459060402685
Maximum:  10.0
Minimum:  0.5
Standard Deviation:  1.7117358608046402


In [118]:
data.describe()

score  release_year  release_month   release_day
count  18625.000000  18625.000000    18625.00000  18625.000000
mean       6.950459   2006.515329        7.13847     15.603866
std        1.711736      4.587529        3.47671      8.690128
min        0.500000   1970.000000        1.00000      1.000000
25%        6.000000   2003.000000        4.00000      8.000000
50%        7.300000   2007.000000        8.00000     16.000000
75%        8.200000   2010.000000       10.00000     23.000000
max       10.000000   2016.000000       12.00000     31.000000

In [120]:
games_number =data['release_year'].value_counts()
print(games_number)

release_year
2008    1915
2009    1687
2007    1610
2010    1363
2006    1208
2005    1088
2011    1073
2000    1045
2004     997
2003     969
2002     936
1999     775
2012     753
2013     696
2001     688
2014     537
2015     365
1998     339
2016     226
1997     205
1996     149
1970       1
Name: count, dtype: int64


In [122]:
phrase =data['score_phrase'].unique()
print(phrase)

['Amazing' 'Great' 'Good' 'Awful' 'Okay' 'Mediocre' 'Bad' 'Painful'
 'Unbearable' 'Disaster' 'Masterpiece']


In [123]:
score_phrase=data['score_phrase'].value_counts()
print(score_phrase)

score_phrase
Great          4773
Good           4741
Okay           2945
Mediocre       1959
Amazing        1804
Bad            1269
Awful           664
Painful         340
Unbearable       72
Masterpiece      55
Disaster          3
Name: count, dtype: int64


In [126]:
plateform=data['platform'].value_counts()
print(plateform)

platform
PC                      3370
PlayStation 2           1686
Xbox 360                1631
Wii                     1366
PlayStation 3           1356
Nintendo DS             1045
PlayStation              952
Wireless                 910
iPhone                   842
Xbox                     821
PlayStation Portable     633
Game Boy Advance         623
GameCube                 509
Game Boy Color           356
Nintendo 64              302
Dreamcast                286
PlayStation 4            277
Nintendo DSi             254
Nintendo 3DS             225
Xbox One                 208
PlayStation Vita         155
Wii U                    114
iPad                      99
Lynx                      82
Macintosh                 81
Genesis                   58
NES                       49
TurboGrafx-16             40
Android                   39
Super NES                 33
NeoGeo Pocket Color       31
N-Gage                    30
Game Boy                  22
iPod                      17
Sega 

In [134]:
ind=data['platform']=='PC'
newData= data[ind]
print("total numbers of pc games are: ",newData.shape[0])


total numbers of pc games are:  3370


In [141]:

amazing_games=(data['score_phrase']=='Amazing') & (data['platform']=='PC')
new_amazing= data[amazing_games]
print("total numbers of amazing games of PC are: ",new_amazing.shape[0])

total numbers of amazing games of PC are:  351
